### ISSUE TITLE
请教 海思3559a 前向forward多长时间呢

### ISSUE THREAD

**Issue by mahxn0** [lrjbdss/CenterTrack_caffe#3]

**Comment by lrjbdss** [comment]
3519a上28ms，3559a没试过

**Comment by mahxn0** [comment]
> 3519a上28ms，3559a没试过

很强了 3559应该可以优化到15ms以内，最近正在尝试直接多目标跟踪，替换传统KCF   非常感谢

**Comment by yolunghiu** [comment]
感谢大佬开源的代码, 请问模型在海思上的部署是由于商业原因没有开源吗? 刚刚接触海思平台, 部署起来有点困难, 大佬能否详细描述一下部署方法?
