### ISSUE TITLE
前一帧

### ISSUE THREAD

**Issue by lyupei** [lrjbdss/CenterTrack_caffe#4]
您好！

我看到代码中连前一帧图像都没有使用吗？

**Comment by lrjbdss** [comment]
https://github.com/lrjbdss/CenterTrack_caffe/blob/b085e5bb1ae3d40f13023b7843e2b33d313be757/src/centerTrack.cpp#L108把当前帧赋给pre_img，做为下一轮的前一帧。

**Comment by lrjbdss** [comment]
[这里](https://github.com/lrjbdss/CenterTrack_caffe/blob/b085e5bb1ae3d40f13023b7843e2b33d313be757/src/centerTrack.cpp#L108)把当前帧赋给pre_img，做为下一轮的前一帧。

**Comment by lyupei** [comment]
> [这里](https://github.com/lrjbdss/CenterTrack_caffe/blob/b085e5bb1ae3d40f13023b7843e2b33d313be757/src/centerTrack.cpp#L108)把当前帧赋给pre_img，做为下一轮的前一帧。

感谢答复。不过我看到pytorchToCaffe中并不支持多输入，是在那个基础上做了修改么

**Comment by lrjbdss** [comment]
[底层](https://github.com/xxradon/PytorchToCaffe/blob/7aa8422eb2b5ac90ceb47e7658814241aa7037b2/pytorch_to_caffe.py#L55)是支持多输入的，稍微该一下就行

**Comment by lyupei** [comment]
好的，感谢！
